language: java
jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "grinfeld-github"
    token:
      secure: "2a0693a9828ee3decf5ecc9e9c7b90b316c44d85" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
