language: java
jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "grinfeld-github"
    token:
      secure: "59f368c9896057f3fd0705d3f0783f30d67712b1" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
